server:
  port: 8080
  error:
    include-message: always

cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"
  exposed-headers: "*"

spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}

  jpa:
    hibernate:
# Hibernate ddl auto (create, create-drop, validate, update)
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

taskboard:
  app:
    jwt_issuer: task-board-api
    jwt_secret: ${JWT_SECRET}
    jwt_expiration_in_minutes: 120

springdoc.packages-to-scan: com.aos.taskboard.controllers
